Repository OpenPerpetuum/PerpetuumServer, pull requests merged in 2019-07, with the labels that each got.

#109 Alliance SAP: reduce effect
  src/Perpetuum/Zones/Intrusion/Outpost.cs
Labels: Patch 12

#105 GM command: change corp name
  src/Perpetuum/Services/Channels/GameAdminCommands.cs
Labels: Patch 12, enhancement

#106 100% Corp tax no longer exits the reward loop
  src/Perpetuum/Services/MissionEngine/Missions/MissionInProgress.cs
Labels: Patch 12, bug
