Repository OpenPerpetuum/PerpetuumServer, pull requests merged in 2019-09, with the labels that each got.

#108 Outpost Stability cap increase + fixes
  src/Perpetuum/Zones/Intrusion/Outpost.cs
Labels: Patch 13, enhancement

#95 Sort a few issues with NPC threat management and EP rewards
  src/Perpetuum/Zones/NpcSystem/Npc.cs
  src/Perpetuum/Zones/NpcSystem/ThreatManager.cs
Labels: Patch 13, bug, help wanted

#107 Event System + SAP-NPCs
  src/Perpetuum.Bootstrapper/PerpetuumBootstrapper.cs
  src/Perpetuum/Perpetuum.csproj
  src/Perpetuum/Services/EventServices/EventListenerService.cs
  src/Perpetuum/Services/EventServices/EventMessages/EventMessage.cs
  src/Perpetuum/Services/EventServices/EventMessages/EventMessageSimple.cs
  src/Perpetuum/Services/EventServices/EventMessages/NpcEventMessage.cs
  src/Perpetuum/Services/EventServices/EventMessages/StabilityEffectMessage.cs
  src/Perpetuum/Services/EventServices/EventProcessors/AffectOutpostStability.cs
  src/Perpetuum/Services/EventServices/EventProcessors/ChatEcho.cs
  src/Perpetuum/Services/EventServices/EventProcessors/EventProcessor.cs
  src/Perpetuum/Zones/Intrusion/Outpost.cs
  src/Perpetuum/Zones/Intrusion/SAP.cs
  src/Perpetuum/Zones/NpcSystem/Flocks/Flock.cs
  src/Perpetuum/Zones/NpcSystem/Flocks/FlockConfiguration.cs
  src/Perpetuum/Zones/NpcSystem/Flocks/FlockConfigurationRepository.cs
  src/Perpetuum/Zones/NpcSystem/Flocks/IFlockConfiguration.cs
  src/Perpetuum/Zones/NpcSystem/Flocks/NormalFlock.cs
  src/Perpetuum/Zones/NpcSystem/NPCBossInfo.cs
  src/Perpetuum/Zones/NpcSystem/Npc.cs
Labels: Feature, Patch 13, WIP, help wanted
