Repository OpenPerpetuum/PerpetuumServer, pull requests merged in 2021-03, with the labels that each got.

#278 Refactor environment effect lookup
  src/Perpetuum/Services/EventServices/EventProcessors/EnvironmentalEffectHandler.cs
  src/Perpetuum/Services/GameTime/GameTimeInfo.cs
  src/Perpetuum/Services/Weather/WeatherInfo.cs
Labels: Refactor

#277 New category flags for new items
  src/Perpetuum.Bootstrapper/PerpetuumBootstrapper.cs
  src/Perpetuum.ExportedTypes/CategoryFlags.cs
  src/Perpetuum.ExportedTypes/DefinitionNames.cs
  src/Perpetuum/Players/Player.cs
Labels: enhancement

#282 Fieldterminal range check bug
  src/Perpetuum.RequestHandlers/Zone/Containers/ZoneContainerRequestHandler.cs
Labels: bug

#283 Email on registration
  src/Perpetuum/Services/Sessions/SessionManager.cs
Labels: bug

#286 Nic for completion of tutorial milestones
  src/Perpetuum/Zones/Teleporting/Strategies/TrainingExitStrategy.cs
Labels: enhancement

#276 Npc event anomaly spawn
  src/Perpetuum.Bootstrapper/PerpetuumBootstrapper.cs
  src/Perpetuum.ExportedTypes/DefinitionNames.cs
  src/Perpetuum/ErrorCodes.cs
  src/Perpetuum/Perpetuum.csproj
  src/Perpetuum/Services/EventServices/EventMessages/SpawnPortalMessage.cs
  src/Perpetuum/Services/EventServices/EventProcessors/PortalSpawner.cs
  src/Perpetuum/Services/RiftSystem/CustomRiftConfig.cs
  src/Perpetuum/Services/RiftSystem/Rift.cs
  src/Perpetuum/Zones/NpcSystem/Flocks/FlockConfigurationRepository.cs
  src/Perpetuum/Zones/NpcSystem/NPCBossInfo.cs
Labels: Feature, Strongholds

#290 Issue 257: Server "Admins only" mode
  src/Perpetuum/Services/Channels/ChatCommands/AdminCommandHandlers.cs
Labels: enhancement

#292 Missionreward rebalance and protect array accessor
  src/Perpetuum/Services/MissionEngine/MissionTargets/MissionTargetRewardCalculator.cs
Labels: Refactor
