Repository OpenPerpetuum/PerpetuumServer, pull requests merged in 2021-04, with the labels that each got.

#295 Fix for Datashard category
  src/Perpetuum.Bootstrapper/PerpetuumBootstrapper.cs
Labels: bug

#299 Itemshop return valid definitions
  src/Perpetuum/Services/ItemShop/ItemShop.cs
Labels: bug

#291 Issue 229: arg check on admincommands
  src/Perpetuum/Services/Channels/ChatCommands/AdminCommandHandlers.cs
Labels: Refactor, WIP

#297 Issue 257: Support for OnlyAllowAdmins as a server startup config
  src/Perpetuum.AdminTool/LocalServerRunner.cs
  src/Perpetuum.RequestHandlers/RelayClose.cs
  src/Perpetuum.RequestHandlers/RelayOpen.cs
  src/Perpetuum/GlobalConfiguration.cs
  src/Perpetuum/Services/Relay/IRelayStateService.cs
  src/Perpetuum/Services/Relay/RelayInfoBuilder.cs
  src/Perpetuum/Services/Relay/RelayStateService.cs
Labels: enhancement

#301 Stronghold Exit Rift overhaul: use TargettedPortal!
  src/Perpetuum.Bootstrapper/PerpetuumBootstrapper.cs
  src/Perpetuum/Collections/WeightedCollection.cs
  src/Perpetuum/Perpetuum.csproj
  src/Perpetuum/Services/EventServices/EventProcessors/PortalSpawner.cs
  src/Perpetuum/Services/RiftSystem/CustomRiftConfig.cs
  src/Perpetuum/Services/RiftSystem/Rift.cs
  src/Perpetuum/Services/RiftSystem/StrongholdRifts/StrongholdExitLocations.cs
  src/Perpetuum/Services/RiftSystem/StrongholdRifts/StrongholdExitRift.cs
  src/Perpetuum/Services/RiftSystem/StrongholdRifts/StrongholdRiftManager.cs
Labels: Feature, Strongholds

#302 Container depth check
  src/Perpetuum.RequestHandlers/Zone/Containers/ZoneContainerRequestHandler.cs
Labels: bug
