Repository OpenPerpetuum/PerpetuumServer, pull requests merged in 2021-10, with the labels that each got.

#391 Npc infestation: growing spawns of npcs
  src/Perpetuum.Bootstrapper/PerpetuumBootstrapper.cs
  src/Perpetuum/ErrorCodes.cs
  src/Perpetuum/Perpetuum.csproj
  src/Perpetuum/Zones/DistanceConstants.cs
  src/Perpetuum/Zones/NpcSystem/Presences/ExpiringStaticPresence/FlockEscalationSelector.cs
  src/Perpetuum/Zones/NpcSystem/Presences/ExpiringStaticPresence/IRandomStaticPresence.cs
  src/Perpetuum/Zones/NpcSystem/Presences/ExpiringStaticPresence/RandomSpawningExpiringPresence.cs
  src/Perpetuum/Zones/NpcSystem/Presences/ExpiringStaticPresence/StaticExpiringFlock.cs
  src/Perpetuum/Zones/NpcSystem/Presences/ExpiringStaticPresence/StaticSpawnState.cs
  src/Perpetuum/Zones/NpcSystem/Presences/GrowingPresences/GrowingNPCBasePresence.cs
  src/Perpetuum/Zones/NpcSystem/Presences/GrowingPresences/GrowingPresence.cs
  src/Perpetuum/Zones/NpcSystem/Presences/GrowingPresences/GrowthStates.cs
  src/Perpetuum/Zones/NpcSystem/Presences/IPresenceConfiguration.cs
  src/Perpetuum/Zones/NpcSystem/Presences/PathFinders/RoamingStates.cs
  src/Perpetuum/Zones/NpcSystem/Presences/PresenceConfiguration.cs
  src/Perpetuum/Zones/NpcSystem/Presences/PresenceConfigurationReader.cs
  src/Perpetuum/Zones/NpcSystem/Presences/PresenceType.cs
  src/Perpetuum/Zones/PBS/PBSDeployer.cs
Labels: Feature, Gamma

#407 new effects, new rule for checking on teleport, robustify presence lo…
  src/Perpetuum.ExportedTypes/AggregateField.cs
  src/Perpetuum.ExportedTypes/EffectType.cs
  src/Perpetuum.RequestHandlers/Zone/TeleportUse.cs
  src/Perpetuum/Units/Unit.cs
  src/Perpetuum/Zones/NpcSystem/Presences/PresenceManager.cs
Labels: enhancement, Gamma

#410 Tech level'd construction blocks
  src/Perpetuum.ExportedTypes/AggregateField.cs
  src/Perpetuum.ExportedTypes/DefinitionNames.cs
  src/Perpetuum/ErrorCodes.cs
  src/Perpetuum/Perpetuum.csproj
  src/Perpetuum/Zones/PBS/ConstructionAmmoHelpers.cs
  src/Perpetuum/Zones/PBS/ConstructionModule.cs
  src/Perpetuum/Zones/PBS/PBSHelper.cs
  src/Perpetuum/Zones/PBS/PBSInterfaces.cs
  src/Perpetuum/Zones/PBS/PBSObjectHelper.cs
Labels: Feature, Gamma

#408 Staging PBS base: expires + other unique rules
  src/Perpetuum.Bootstrapper/PerpetuumBootstrapper.cs
  src/Perpetuum.ExportedTypes/DefinitionNames.cs
  src/Perpetuum/EntityFramework/EntityRepositoryExtensions.cs
  src/Perpetuum/ErrorCodes.cs
  src/Perpetuum/Perpetuum.csproj
  src/Perpetuum/Services/ProductionEngine/Facilities/ProductionFacility.cs
  src/Perpetuum/Zones/DistanceConstants.cs
  src/Perpetuum/Zones/PBS/DockingBases/ExpiringPBSDockingBase.cs
  src/Perpetuum/Zones/PBS/DockingBases/PBSDockingBase.cs
  src/Perpetuum/Zones/PBS/PBSEgg.cs
  src/Perpetuum/Zones/PBS/PBSHelper.cs
  src/Perpetuum/Zones/PBS/PBSObjectHelper.cs
Labels: help wanted, Feature, Gamma

#395 issue 312: Make a HarvestingLogHandler and HarvestLog table
  src/Perpetuum.Bootstrapper/PerpetuumBootstrapper.cs
  src/Perpetuum/Modules/HarvesterModule.cs
  src/Perpetuum/Perpetuum.csproj
  src/Perpetuum/Zones/HarvestLogHandler.cs
  src/Perpetuum/Zones/IZone.cs
  src/Perpetuum/Zones/Zone.cs
Labels: enhancement

#416 ZoneDrawBlockingByDefinition enhancement
  src/Perpetuum.RequestHandlers/Zone/ZoneDrawBlockingByDefinition.cs
  src/Perpetuum/Services/Channels/ChatCommands/AdminCommandHandlers.cs
Labels: enhancement, Gamma
