Repository OpenPerpetuum/PerpetuumServer, pull requests merged in 2021-11, with the labels that each got.

#421 Markdown updates
  CONTRIBUTING.md
  LICENSE
  README.md
Labels: Difficulty: Easy, Priority: Low

#400 added scaling value for plant repopulation timer
  src/Perpetuum/Zones/Eggs/AreaBomb.cs
  src/Perpetuum/Zones/Terrains/Materials/Plants/PlantHandler.cs
Labels: enhancement, performance

#427 DynamicPresExtended: spawn location noise
  src/Perpetuum/Zones/NpcSystem/Flocks/RemoteSpawningFlock.cs
Labels: enhancement, Gamma, Difficulty: Easy, Priority: Medium

#431 Aggro tweaks
  src/Perpetuum/Modules/ArmorRepairModule.cs
  src/Perpetuum/Services/EventServices/EventProcessors/NpcSpawnEventHandlers/NpcReinforcementSpawner.cs
Labels: Gamma, Difficulty: Easy

#434 Npc aggro refactor and enhancement
  src/Perpetuum/Perpetuum.csproj
  src/Perpetuum/Zones/NpcSystem/Npc.cs
  src/Perpetuum/Zones/NpcSystem/PrimaryTargetStrategy.cs
Labels: Gamma, Difficulty: Moderate

#442 Staging terminal: no wall/gate
  src/Perpetuum/Zones/PBS/PBSHelper.cs
Labels: bug, Gamma, Difficulty: Easy, Priority: High

#443 Staging term expire time persistence
  src/Perpetuum/Zones/PBS/DockingBases/ExpiringPBSDockingBase.cs
Labels: Gamma, Difficulty: Moderate, Priority: High

#445 NPC fixes
  src/Perpetuum/Zones/NpcSystem/Npc.cs
Labels: bug, Priority: High

#449 PBS base limit check fixes
  src/Perpetuum/Zones/PBS/PBSHelper.cs
Labels: bug, Gamma, Priority: High

#451 ExpiringPBSBase while in reinforce fix
  src/Perpetuum/Zones/PBS/DockingBases/ExpiringPBSDockingBase.cs
Labels: bug, Gamma, Difficulty: Easy, Priority: High

#452 ExpiringBase: disallow deconstruction state change command
  src/Perpetuum/Zones/PBS/DockingBases/ExpiringPBSDockingBase.cs
  src/Perpetuum/Zones/PBS/DockingBases/PBSDockingBase.cs
Labels: bug, Gamma

#453 Staging Terminal chat warnings/info, mail to corp officers
  src/Perpetuum/Units/DockingBases/DockingBase.cs
  src/Perpetuum/Zones/PBS/DockingBases/ExpiringPBSDockingBase.cs
Labels: enhancement, Gamma, Difficulty: Moderate, Priority: High
